# Generated by Django 3.0.7 on 2020-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('plate_id', models.CharField(max_length=200)),
                ('violation_code', models.CharField(max_length=200)),
                ('drone_id', models.IntegerField()),
            ],
        ),
    ]
